version: '3.1'
services:
  php:
    image: webdevops/php-nginx:7.2
    ports:
      - '$HTTP_PORT:80'
      - '$HTTPS_PORT:443'
    volumes:
      - ./app:/app:delegated
    environment:
      - DUID=1000
      - GDID=1000
      - WEB_DOCUMENT_ROOT=/app/web
      - WEB_ALIAS_DOMAIN=$APP_URL

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
